// <auto-generated />
using System;
using Kriteriom.BatchProcessor.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kriteriom.BatchProcessor.Migrations
{
    [DbContext(typeof(BatchDbContext))]
    [Migration("20260418005141_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kriteriom.BatchProcessor.Persistence.BatchJobCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_name");

                    b.Property<int>("LastProcessedOffset")
                        .HasColumnType("integer")
                        .HasColumnName("last_processed_offset");

                    b.Property<int>("ProcessedRecords")
                        .HasColumnType("integer")
                        .HasColumnName("processed_records");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer")
                        .HasColumnName("total_records");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JobName")
                        .HasDatabaseName("ix_batch_job_checkpoints_job_name");

                    b.ToTable("batch_job_checkpoints", (string)null);
                });

            modelBuilder.Entity("Kriteriom.BatchProcessor.Persistence.BatchJobLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_name");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("JobName")
                        .HasDatabaseName("ix_batch_job_logs_job_name");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_batch_job_logs_timestamp");

                    b.ToTable("batch_job_logs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
